"""
Are visual and gyroscopic rotation errors INHERENTLY correlated?

On real UZH-FPV flight the two error sources correlate at rho = +0.64, which
caps the achievable fusion gain at ~2.5%. Every candidate explanation was
eliminated: angular rate, rotation magnitude, frame interval, feature count,
ground-truth noise (0.0002 deg), the camera-IMU extrinsic, and timing offset.

The simulator settles it, because here the two error sources are generated by
provably independent random processes:

  * gyro error  <- injected white noise + bias random walk (known realisation)
  * visual error <- feature localisation and two-view geometry
  * ground truth <- analytic, exact; it contributes NO error at all

If the measured correlation comes out near zero, the real-data coupling is an
artifact of the real pipeline and can be hunted directly. If it reproduces at
~0.6 under independent generation, the coupling is a property of how the two
estimators respond to a shared stimulus, which is a genuine finding.

Consistency note: the renderer is a pinhole camera, so this experiment uses a
PINHOLE rotation estimator. The real-data path applies the equidistant fisheye
model. Mixing the two would invalidate the comparison.
"""
import sys

import cv2
import numpy as np
from scipy import stats

sys.path.insert(0, 'vio')

from horizon_analysis import GyroIntegrator, angular_error_deg      # noqa: E402
from visual_horizon import ChainedTracker                           # noqa: E402

from .scene import Camera                                           # noqa: E402
from .sensors import render_blurred                                 # noqa: E402
from .trajectory import Trajectory, ImuModel                        # noqa: E402
from .worlds import corridor, add_obstacles                         # noqa: E402


def rotation_pinhole(p0, p1, K):
    """Essential-matrix rotation for a true pinhole camera (no undistortion)."""
    if len(p0) < 8:
        return None
    E, mask = cv2.findEssentialMat(p0, p1, K, method=cv2.RANSAC,
                                   prob=0.99, threshold=1.0, maxIters=300)
    if E is None or E.shape != (3, 3):
        return None
    inliers, R_pts, _, _ = cv2.recoverPose(E, p0, p1, K, mask=mask)
    if inliers < 6:
        return None
    return R_pts.T


def run(duration=6.0, peak_omega=4.1, speed=5.0, frame_hz=30.0,
        gyro_noise_density=0.043, exposure=0.010, blur_samples=6,
        seed=0, verbose=True):
    cam = Camera.davis346()
    scene = add_obstacles(corridor(seed=seed), count=8, seed=100 + seed)
    traj = Trajectory(peak_omega=peak_omega, omega_hz=0.6, speed=speed)

    imu = ImuModel(gyro_noise_density=gyro_noise_density,
                   seed=seed + 1).sample(traj, duration)
    gyro = GyroIntegrator(imu['t'], imu['gyro'])

    frame_t = np.arange(0.0, duration, 1.0 / frame_hz)
    tracker = ChainedTracker()
    for i, t in enumerate(frame_t):
        img, _ = render_blurred(scene, cam, traj, t, exposure,
                                blur_samples, duration)
        tracker.process(img)
        if verbose and i % 40 == 0:
            print(f'  rendered {i}/{len(frame_t)}', flush=True)

    R_true = traj.rotation(frame_t, duration)

    eg, ev, thetas, Eg, Ev = [], [], [], [], []
    for i in range(len(frame_t) - 1):
        R_gt = R_true[i].T @ R_true[i + 1]
        a, b = tracker.positions[i], tracker.positions[i + 1]
        shared = sorted(set(a) & set(b))
        if len(shared) < 8:
            continue
        p0 = np.array([a[j] for j in shared], np.float32)
        p1 = np.array([b[j] for j in shared], np.float32)
        R_vis = rotation_pinhole(p0, p1, cam.K)
        if R_vis is None:
            continue
        R_gyro = gyro.R_rel(frame_t[i], frame_t[i + 1])
        eg.append(angular_error_deg(R_gyro, R_gt))
        ev.append(angular_error_deg(R_vis, R_gt))
        thetas.append(np.degrees(np.arccos(
            np.clip((np.trace(R_gt) - 1) / 2, -1, 1))))
        Eg.append(cv2.Rodrigues(R_gyro @ R_gt.T)[0].ravel())
        Ev.append(cv2.Rodrigues(R_vis @ R_gt.T)[0].ravel())

    return (np.array(eg), np.array(ev), np.array(thetas),
            np.array(Eg), np.array(Ev))


def main():
    print('Simulating controlled flight (exact ground truth, independent noise)...')
    eg, ev, theta, Eg, Ev = run()

    rho = stats.spearmanr(eg, ev).statistic
    cos = np.einsum('ij,ij->i', Eg, Ev) / (
        np.linalg.norm(Eg, axis=1) * np.linalg.norm(Ev, axis=1) + 1e-12)
    vec_angle = np.degrees(np.arccos(np.clip(np.median(cos), -1, 1)))

    print()
    print(f'n = {len(eg)}   median true rotation {np.median(theta):.1f} deg/frame')
    print(f'  gyro   median error {np.median(eg):.4f} deg')
    print(f'  vision median error {np.median(ev):.4f} deg')
    print()
    print(f'  SIM  rho(gyro err, vision err)      = {rho:+.3f}')
    print('  REAL rho(gyro err, vision err)      = +0.641')
    print(f'  SIM  median angle between err vecs  = {vec_angle:.1f} deg')
    print('  REAL median angle between err vecs  = 34.2 deg   (90 = independent)')
    print()
    if abs(rho) < 0.25:
        print('  => SIM shows INDEPENDENT errors under provably independent generation.')
        print('     The real-data coupling is therefore an artifact of the real')
        print('     pipeline or the real sensors, not an inherent property of')
        print('     visual-inertial rotation estimation.')
    else:
        print('  => SIM REPRODUCES the coupling despite independent noise sources.')
        print('     The correlation is then inherent to how the two estimators')
        print('     respond to the same motion, and caps fusion gain in general.')


if __name__ == '__main__':
    main()
